#!/bin/bash
# drupal-deploy - Bash script to invoke deploy-drupal utility

PROJECT_ROOT=`dirname "$0"`
export PYTHONPATH="$PROJECT_ROOT/src:$PROJECT_ROOT/lib/PyWizard/src"

/usr/bin/python "$PROJECT_ROOT/src/drupal-deploy.py" $@