#!/usr/bin/python
'''
dt_init - Initialize project directory
'''

from ddt.cmds.InitProject import InitProject
from ddt.cmds.CommandBase import commandline_exec


if __name__ == '__main__':
    commandline_exec(InitProject())